#Villager will transform into a cod when switching back to "NONE" profession (default villager)
ActivateKillVillagerProfessionSetNone: true
#1 out of "KillVillagerProfessionSetNoneChance" villager profession sets to "NONE" be safe from being removed, if "ActivateKillVillagerProfessionSetNone" is true
#this nerfs both villager career switching, and zombie villager curing (since cured villager gets set to NONE profession on revive)
KillVillagerProfessionSetNoneChance: 3
#Villager reproduction will be interrupted a configured amount of times
ReduceVillagerBreeding: true
#1 out of "InterruptVillagerReproductionChance" villager reproductions will get cancelled, if "ReduceVillagerBreeding" is set to true
InterruptVillagerReproductionChance: 10
#Divide max trades per trade, for all trades, in order to nerf all item max amounts globally. Leave at 1 to disable
MaxTradesNerfDivider: 2
#How many interactions with a Master level villager until locked trades become very common:
EnhancedTradeLockingAfterThresholdInteractions: 3
#1 out of "TimesTradesLocked" after "EnhancedTradeLockingAfterThresholdInteractions" is reached, the trades won't be locked
TimesTradesLocked: 20
#If a chance should be applied for enchanted books to be unlocked
ActivateEnchantedBookChance: true
#1 out of "EnchantedBookChance" trades will be unlocked if "EnchantedBookChanceActive" is true
EnchantedBookChance: 10