#Disable villager trade stock replenishing:
NerfVillagerRestock: true
#Time global restock (divided by 3, multiplied by 2, multiplied by online player amount):

#Disable villager breeding:
#DisableVillagerBreeding: true
