#Villager will transform into a vindicator when switching back to "NONE" profession (default villager)
ActivateKillVillagerProfessionSetNone: true
#1 out of "KillVillagerProfessionSetNoneChance" villager profession sets to "NONE" be safe from being removed, if "ActivateKillVillagerProfessionSetNone" is true
#this nerfs villager career switching, zombie villager curing, and villager reproduction (since cured villager gets set to NONE profession on revive and birth)
KillVillagerProfessionSetNoneChance: 2
#Villager reproduction will be interrupted a configured amount of times
ReduceVillagerBreeding: true
#1 out of "InterruptVillagerReproductionChance" villager reproductions will get cancelled, if "ReduceVillagerBreeding" is set to true
InterruptVillagerReproductionChance: 20
#Divide max trades per trade, for all trades, in order to nerf all item max amounts globally. Leave at 1 to disable
MaxTradesNerfDivider: 2
#How many interactions with a Master level villager until locked trades become very common:
EnhancedTradeLockingAfterThresholdInteractions: 3
#1 out of "TimesTradesLocked" after "EnhancedTradeLockingAfterThresholdInteractions" is reached, the trades won't be locked
TimesTradesLocked: 20
#The following drop rates are applied to the base vanilla drop rate, so if an item had been dropped in vanilla,
#an extra chance is rolled within that drop rate:
PillagerEmeraldDropRate: 0.05
VindicatorEmeraldDropRate: 0.05
EvokerEmeraldDropRate: 0.25
EvokerTotemDropRate: 0.025